{{- if and .Values.rds .Values.rds.clusters }}
{{- range .Values.rds.clusters }}
---
# ============================================================================
# PushSecret - Sync RDS credentials to AWS Secrets Manager
# ============================================================================
# This resource runs in the TOOLS cluster and pushes Crossplane-generated
# RDS credentials to the QA/Prod AWS account's Secrets Manager.
#
# Flow:
#   1. Crossplane creates RDS and writes connection secret to tools cluster
#   2. PushSecret reads that secret and pushes to QA/Prod Secrets Manager
#   3. Apps in QA/Prod cluster pull via ExternalSecret
# ============================================================================

apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ .name }}-push-secret
  namespace: {{ $.Values.global.namespace | default "crossplane-system" }}
  labels:
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/managed-by: crossplane
    environment: {{ $.Values.global.environment }}
  annotations:
    argocd.argoproj.io/sync-wave: "15"  # Deploy after RDS cluster is ready
spec:
  refreshInterval: 30s  # Check for secret updates every 30 seconds

  # Use environment-specific ClusterSecretStore (aws-secretsmanager-qa or aws-secretsmanager-prod)
  # This provides cross-account access to write to QA/Prod Secrets Manager
  secretStoreRefs:
    - name: aws-secretsmanager-{{ $.Values.global.environment }}
      kind: ClusterSecretStore

  # Source: Read the Crossplane-generated connection secret
  selector:
    secret:
      name: {{ .name }}-connection-info

  # Destination: Push as plain text JSON string to AWS Secrets Manager
  # Path: rds/{environment}/{cluster-name}
  data:
    - match:
        secretKey: endpoint
        remoteRef:
          remoteKey: {{ $.Values.global.environment }}/rds/{{ .name }}
          property: POSTGRES_HOST
    - match:
        secretKey: port
        remoteRef:
          remoteKey: {{ $.Values.global.environment }}/rds/{{ .name }}
          property: POSTGRES_PORT
    - match:
        secretKey: master_username
        remoteRef:
          remoteKey: {{ $.Values.global.environment }}/rds/{{ .name }}
          property: POSTGRES_USER
    - match:
        secretKey: attribute.master_password
        remoteRef:
          remoteKey: {{ $.Values.global.environment }}/rds/{{ .name }}
          property: POSTGRES_PASSWORD
    - match:
        secretKey: reader_endpoint
        remoteRef:
          remoteKey: {{ $.Values.global.environment }}/rds/{{ .name }}
          property: POSTGRES_HOST_READ_ONLY

{{- end }}
{{- end }}
