{{- if and .Values.rds .Values.rds.clusters }}
{{- range .Values.rds.clusters }}
{{- if and .syncToSecretsManager .syncToSecretsManager.enabled }}
---
# ============================================================================
# TOOLS CLUSTER RESOURCES
# These resources are deployed to the tools cluster (where Crossplane runs)
# They read Crossplane-generated secrets and push them to AWS Secrets Manager
# ============================================================================

# PushSecret: Reads Crossplane connection secrets and pushes to AWS Secrets Manager
# This runs in the tools cluster alongside Crossplane
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ .name }}-connection-push
  namespace: {{ $.Values.global.namespace | default "crossplane-system" }}
  labels:
    helm.sh/chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/managed-by: crossplane
    environment: {{ $.Values.global.environment }}
    cluster: tools
spec:
  refreshInterval: 10s
  secretStoreRefs:
    - name: {{ .syncToSecretsManager.secretStoreRef | default "aws-secretsmanager" }}
      kind: {{ .syncToSecretsManager.secretStoreKind | default "ClusterSecretStore" }}
  selector:
    secret:
      name: {{ .name }}-connection-info
  data:
    - match:
        secretKey: ".*"
        remoteRef:
          remoteKey: {{ .syncToSecretsManager.remoteKeyPrefix | default (printf "rds/%s/%s" $.Values.global.environment .name) }}
{{- end }}

{{- end }}
{{- end }}
