apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qa
spec:
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
  secretName: qa-certificate
  dnsNames:
  - gaiadynamics.ai
