{{- if $.Values.app.autoscaling }}
{{- if and $.Values.app.autoscaling.enabled (not $.Values.app.suspended) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Values.app.name }}
  namespace: {{ printf "sid-%s" $.Values.app.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $.Values.app.name }}
  minReplicas: {{ $.Values.app.autoscaling.minReplicas }}
  maxReplicas: {{ $.Values.app.autoscaling.maxReplicas }}
  metrics:
    {{- if $.Values.app.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $.Values.app.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- if $.Values.app.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $.Values.app.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
