{{- if $.Values.autoscaling }}
{{- if and $.Values.autoscaling.enabled (not $.Values.suspended) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $.Values.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $.Values.name }}
  minReplicas: {{ $.Values.autoscaling.minReplicas }}
  maxReplicas: {{ $.Values.autoscaling.maxReplicas }}
  metrics:
    {{- if $.Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $.Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- if $.Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $.Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ $.Values.autoscaling.scaleUpStabilizationWindowSeconds | default 120 }}
      policies:
        - type: Pods
          value: {{ $.Values.autoscaling.scaleUpPods | default 4 }}
          periodSeconds: {{ $.Values.autoscaling.scaleUpPeriodSeconds | default 60 }}
    scaleDown:
      stabilizationWindowSeconds: {{ $.Values.autoscaling.scaleDownStabilizationWindowSeconds | default 600 }}
      policies:
        - type: Pods
          value: {{ $.Values.autoscaling.scaleDownPods | default 2 }}
          periodSeconds: {{ $.Values.autoscaling.scaleDownPeriodSeconds | default 120 }}
{{- end }}
{{- end }}
