{{- if .Values.service -}}
{{ $length := len .Values.service.ports }} {{ if gt $length 0 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ printf "sid-%s" .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  ports:
    {{- range $value := .Values.service.ports }}
    - port: {{ $value }}
      targetPort: {{ $value }}
      protocol: TCP
      name: {{ printf "port-%s-tcp" $value }}
    {{- end }}

  selector:
    app: {{ .Values.name }}
    env: {{ .Values.environment }}
{{- end }}
{{- end }}
