apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ printf "arn:aws:iam::%s:role/%s-%s" $.Values.aws.accountId $.Values.name $.Values.environment }}
  name: {{ $.Values.name }}
