{{- if $.Values.app.service -}}
{{ $length := len $.Values.app.service.ports }} {{ if gt $length 0 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.app.name }}
  namespace: {{ printf "sid-%s" $.Values.app.namespace }}
  labels:
    app: {{ $.Values.app.name }}
spec:
  ports:
    {{- range $value := $.Values.app.service.ports }}
    - port: {{ $value }}
      targetPort: {{ $value }}
      protocol: TCP
      name: {{ printf "port-%s-tcp" $value }}
    {{- end }}

  selector:
    app: {{ $.Values.app.name }}
    env: {{ $.Values.app.environment }}
{{- end }}
{{- end }}
