apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ printf "arn:aws:iam::%s:role/%s-%s" (include "app.awsAccountId" .) $.Values.app.name $.Values.app.environment }}
  name: {{ $.Values.name }}
